server:
  port: 80
  servlet:
    session:
      timeout: 360
spring:
  session:
#    store-type: redis
#    redis:
#      flush-mode: on-save
#      namespace: spring:session
#      host: localhost
#      port: 6379
#      password: admin
